export const ItemDetail1 = [
  {
    img: "https://m.media-amazon.com/images/I/91pzohpvYIL._SX3000_.jpg",
    caption: "Slide 1",
  },
  {
    img: " https://m.media-amazon.com/images/I/81Kqplt2UzL._SX3000_.jpg ",
    caption: "Slide 2",
  },
  {
    img: " https://m.media-amazon.com/images/I/61h3+J34oWL._SX3000_.jpg ",
    caption: "Slide 3",
  },
  {
    img: " https://m.media-amazon.com/images/I/51ovs76vmtL._SX3000_.jpg ",
    caption: "Slide 4",
  },
  {
    img: " https://m.media-amazon.com/images/I/613-gA49v1L._SX3000_.jpg ",
    caption: "Slide 5",
  },
];

export const ItemDetail2 = [
  {
    name: "HP 14s-dr3001TU Laptop (Intel Pentium Silver N6000/8 GB/256 GB SSD/UHD Graphics/Windows 11 Home/MSO/HD), 35.6 cm (14 inch)",
    img: "https://www.reliancedigital.in/medias/Hp-681Y7PA-ACJ-Laptop-493178767-i-1-1200Wx1200H-300Wx300H?context=bWFzdGVyfGltYWdlc3wyNjAxOXxpbWFnZS9qcGVnfGltYWdlcy9oYTQvaDU2Lzk5MjM5NDA2MTQxNzQuanBnfGEzZDE5OGQxNmY4M2FkMGUxODU2OTg4MDdkOTFkMmZlYmJmZjdiMDAzZTVhYzBiZmVmNThiMmYwYzhmMTkyNGI",
    price: "32,999.00",
    mrp: "37,000.00",
    discount: "11%(₹4,001)",
    id: 1,
    linked: "laptops",
  },
  {
    name: "HP 15s-er1501AU Standard Laptop (AMD Ryzen 3 3250U/8 GB/256 GB SSD/Radeon Graphics/Windows 11 Home/MSO/HD), 39.62 cm (15.6 Inch)",
    img: "https://www.reliancedigital.in/medias/HP-ER1501AU-Laptop-493178397-i-1-1200Wx1200H-300Wx300H?context=bWFzdGVyfGltYWdlc3w1ODU4NnxpbWFnZS9qcGVnfGltYWdlcy9oNmUvaDIyLzk5MDE1NTA5Mjc5MDIuanBnfDlkOGRhZGEyOWMyZWQzNTI2YTc4ZTY5ODJhYjBlNTRlZDg5YmQ5YTczM2Q2MTg0ZGRkYTE3Y2IyMmI1NTQzMDY",
    price: "28,990.00",
    mrp: "41,204.00",
    discount: "30%(₹12,214)",
    id: 2,
    linked: "laptops",
  },
  {
    name: "Lenovo L2IN IdeaPad 3 Laptop (11th Gen Intel Core i3-1115G4 /8GB/256GB SSD/Intel UHD Graphics/Windows 11/MSO/Full HD), 39.62 cm (15.6 inch)",
    img: "https://www.reliancedigital.in/medias/Lenovo-L2IN-Laptops-492574725-i-1-1200Wx1200H-300Wx300H?context=bWFzdGVyfGltYWdlc3w2MTQ2NnxpbWFnZS9qcGVnfGltYWdlcy9oZmIvaGQyLzk3NDczMjk5NzQzMDIuanBnfDMxMDY2NDQ1MjE3ZDFjOTZiNjRmYTE0NTlhNmYzMWZmNGNjNjY3NzhkZjE2MTdlZTZmMzE2Yjc3NDBmNjYwMGU",
    price: "35,499.00",
    mrp: "59,390.00",
    discount: "40%(₹23,891)",
    id: 3,
    linked: "laptops",
  },
  {
    name: "HP 15s-fq2670TU Laptop (11th Gen Intel Core i3-1115G4/8 GB RAM/256 GB SSD/Windows 11 Home/MSO/FHD), 39.6 cm (15.6 inch)",
    img: "https://www.reliancedigital.in/medias/Hp-6N043PA-ACJ-Laptop-493177597-i-1-1200Wx1200H-300Wx300H?context=bWFzdGVyfGltYWdlc3wyOTkyOHxpbWFnZS9qcGVnfGltYWdlcy9oNjIvaDZhLzk4ODIyODk1MzcwNTQuanBnfDAzZjY0ZjBmY2RmNWY0YzBiMWU5MGQ1YTkxYWIxMmVhZGJmYTdkNDFkYWRiMGMwNzNhOTlhNzFmM2EzNWQxZGE",
    price: "41,400.00",
    mrp: "45,409.00",
    discount: "9%(₹4,009)",
    id: 4,
    linked: "laptops",
  },
  {
    name: "Lenovo LJIN IdeaPad 3 Laptop (11th Gen Intel Core i3-1115G4/8GB/512GB SSD/Intel UHD Graphics/Windows 11/MSO/Full HD), 39.62 cm (15.6 inch)",
    img: "https://www.reliancedigital.in/medias/Lenovo-LJIN-Laptops-492574616-i-1-1200Wx1200H-300Wx300H?context=bWFzdGVyfGltYWdlc3w2ODcxN3xpbWFnZS9qcGVnfGltYWdlcy9oYjAvaGJiLzk3NDE1NjMzOTYxMjYuanBnfDk3NmMzMWI4MDZjYzU0YzJmZGUxNTJiYzI0MGRjOTQ5Nzg5ZjI1YmM3NzNmNmE3NjQ3ZTQ0NzlhMzI2ZDNlYzU",
    price: "40,499.00",
    mrp: "65,690.00",
    discount: "38%(₹25,191)",
    id: 5,
    linked: "laptops",
  },
  {
    name: "Lenovo IdeaPad 3 Thin and Light Laptop (11th Gen Intel Core i3-1115G4/8 GB/512 GB SSD/Windows 11 Home/MSO/FHD), 39.62 cm (15.6 Inch)",
    img: "https://www.reliancedigital.in/medias/Lenovo-82H802L3IN-Laptop-493177740-i-1-1200Wx1200H-300Wx300H?context=bWFzdGVyfGltYWdlc3wyNTg4M3xpbWFnZS9qcGVnfGltYWdlcy9oZjcvaDk4Lzk4OTQ2NDQyNTI3MDIuanBnfDUwOTkxZTdiMWYxZjVmY2M3YWI3NDRhZDVjYjViYzMwNzZjZDE4OTk4NGM2YjM2YjkxZmE5OGU5NTgxYzI3NDg",
    price: "38,990.00",
    mrp: "67,090.00",
    discount: "42%(₹28,100)",
    id: 6,
    linked: "laptops",
  },
  {
    name: "HP 15s-fq2672TU Laptop (11th Gen Intel Core i3-1115G4/8GB RAM/512GB SSD/UHD Graphics/Windows 11 Home/MSO/FHD), 39.6 cm (15.6 Inch), Natural Silver",
    img: "https://www.reliancedigital.in/medias/HP-6N045PA-ACJ-Laptop-492850808-i-1-1200Wx1200H-300Wx300H?context=bWFzdGVyfGltYWdlc3wzMDMwM3xpbWFnZS9qcGVnfGltYWdlcy9oMzEvaGZjLzk4NjQyNzcyMjk1OTguanBnfGE5ZjgwMzdjYzY2MTAyMzhiZWRmNzM3OWI0NTNiMWI2MjcyNTRjMjIwNmY5ZmVlMmQwMDE3MjEyNzVmMDRmMTg",
    price: "43,749.00",
    mrp: "49,977.00",
    discount: "12%(₹6,228)",
    id: 7,
    linked: "laptops",
  },
  {
    name: "HP 15s-fq2671TU Laptop (11th Gen Intel Core i3-1115G4/8 GB RAM/512 GB SSD/Windows 11 Home/MSO/FHD), 39.6 cm (15.6 inch)",
    img: "https://www.reliancedigital.in/medias/Hp-6N044PA-ACJ-Laptop-493177596-i-1-1200Wx1200H-300Wx300H?context=bWFzdGVyfGltYWdlc3wyOTYwMHxpbWFnZS9qcGVnfGltYWdlcy9oYTIvaDMwLzk4ODIyOTA4NDc3NzQuanBnfDgzNzE4ZTExMDNkZmY1YmM2MzQyMWUwY2Y2NGRjMTA1MDJjNDVkNjQ5MTk0ZWIyMTA2NWQwY2I2MWNjOGQzZWI",
    price: "39,999.00",
    mrp: "47,833.00",
    discount: "16%(₹7,834)",
    id: 8,
    linked: "laptops",
  },
  {
    name: "Asus EK522WS Laptop (11th Gen Intel Core i5-1135G7/8 GB/512 GB SSD/Iris Xe Graphics/Windows 11 Home/MSO/FHD), 35.56 cm (14 Inch)",
    img: "https://www.reliancedigital.in/medias/Asus-X415EA-EK522WS-Laptop-493178259-i-1-1200Wx1200H-300Wx300H?context=bWFzdGVyfGltYWdlc3wyNTUyNHxpbWFnZS9qcGVnfGltYWdlcy9oZWQvaDM5Lzk5MDQ3MzE1MjEwNTQuanBnfDk2NmRmZTZjNzNiMTlkMjgwMWJiM2E0NjdmOTM4NzJjM2Y5ZTAyZmJmMjZhYmIxYmJjZTVjYzNkMDlmMDE1YWQ",
    price: "49,999.00",
    mrp: "70,990.00",
    discount: "30%(₹20,991)",
    id: 9,
    linked: "laptops",
  },
  {
    name: "HP 15s-fq5111TU Laptop (12th Gen Intel Core i5-1235U/8 GB RAM/512 GB SSD/Windows 11 Home/MSO/FHD), 39.6 cm (15.6 inch)",
    img: "https://www.reliancedigital.in/medias/Hp-6P129PA-ACJ-Laptop-493177598-i-1-1200Wx1200H-300Wx300H?context=bWFzdGVyfGltYWdlc3wyOTYxMnxpbWFnZS9qcGVnfGltYWdlcy9oMzIvaDBjLzk4ODIyODk4NjQ3MzQuanBnfDc4ZGI4NTAzOGE1MWFhMTkyZTUxNGEzNjhlYTExMTA5YjEwNDFkNjVjNWVhNTAzZTkxNDE0YTNhZWFiZTIwZGQ",
    price: "57,928.00",
    mrp: "67,831.00",
    discount: "15%(₹9,903)",
    id: 10,
    linked: "laptops",
  },
  {
    name: "HP 15s-fr5007TU Laptop (12th Gen Intel Core i5-1235U/8GB RAM/512GB SSD/Iris Xe Graphics/Windows 11 Home/MSO/FHD), 39.6 cm (15.6 Inch), Natural Silver",
    img: "https://www.reliancedigital.in/medias/HP-6P130PA-ACJ-Laptop-493177048-i-1-1200Wx1200H-300Wx300H?context=bWFzdGVyfGltYWdlc3wzMDMwM3xpbWFnZS9qcGVnfGltYWdlcy9oMzYvaDBkLzk4NjQyNzY5MDE5MTguanBnfGMxNGRkOTVkMjdmOGJjODBhZGIzYTFkNmQ1OTJmYjE5MjdhMmQ1Y2FmMzIyNGY2ODAwMGNiYTRjZDMyMDY4MmE",
    price: "60,499.00",
    mrp: "68,000.00",
    discount: "11%(₹7,501)",
    id: 11,
    linked: "laptops",
  },
  {
    name: "Asus EK562WS Laptop (11th Gen Intel Core i5-1135G7/8GB+32GB Intel Optane/512GB SSD/Intel Iris Xe Graphics/Windows 11/MSO/Full HD), 35.56 cm (14 inch)",
    img: "https://www.reliancedigital.in/medias/Asus-EK562WS-Laptop-492574733-i-1-1200Wx1200H-300Wx300H?context=bWFzdGVyfGltYWdlc3w0NDQwM3xpbWFnZS9qcGVnfGltYWdlcy9oYjYvaGE4Lzk3NTEzNTk1ODYzMzQuanBnfDI2ZGEyZjEyZTUyMWQxMGM5ODMyMjQwMzI4YTVmNjE1ZTZjNWNkMjkzYTMyODk0YmNiNzYzNWE0MmVmMzUxNDA",
    price: "48,990.00",
    mrp: "69,990.00",
    discount: "30%(₹21,000)",
    id: 12,
    linked: "laptops",
  },
];

export const ItemDetail3 = [
  {
    title: "lighting ceiling kitchen",
    linked: "lighting",
    price: 30,
    discountPercentage: 14.89,
    rating: 4.83,
    thumbnail: "https://i.dummyjson.com/data/products/96/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/96/1.jpg",
      "https://i.dummyjson.com/data/products/96/2.jpg",
      "https://i.dummyjson.com/data/products/96/3.jpg",
      "https://i.dummyjson.com/data/products/96/4.jpg",
      "https://i.dummyjson.com/data/products/96/thumbnail.jpg",
    ],
  },
  {
    title: "Metal Ceramic Flower",
    linked: "lighting",
    price: 35,
    discountPercentage: 10.94,
    rating: 4.93,
    brand: "Ifei Home",
    thumbnail: "https://i.dummyjson.com/data/products/97/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/97/1.jpg",
      "https://i.dummyjson.com/data/products/97/2.jpg",
      "https://i.dummyjson.com/data/products/97/3.jpg",
      "https://i.dummyjson.com/data/products/97/4.webp",
      "https://i.dummyjson.com/data/products/97/thumbnail.jpg",
    ],
  },
  {
    title: "3 lights lndenpant kitchen islang",
    linked: "lighting",
    price: 34,
    discountPercentage: 5.92,
    rating: 4.99,
    thumbnail: "https://i.dummyjson.com/data/products/98/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/98/1.jpg",
      "https://i.dummyjson.com/data/products/98/2.jpg",
      "https://i.dummyjson.com/data/products/98/3.jpg",
      "https://i.dummyjson.com/data/products/98/4.jpg",
      "https://i.dummyjson.com/data/products/98/thumbnail.jpg",
    ],
  },
  {
    title: "American Vintage Wood Pendant Light",
    linked: "lighting",
    price: 46,
    discountPercentage: 8.84,
    rating: 4.32,
    thumbnail: "https://i.dummyjson.com/data/products/99/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/99/1.jpg",
      "https://i.dummyjson.com/data/products/99/2.jpg",
      "https://i.dummyjson.com/data/products/99/3.jpg",
      "https://i.dummyjson.com/data/products/99/4.jpg",
      "https://i.dummyjson.com/data/products/99/thumbnail.jpg",
    ],
  },
  {
    title: "Crystal chandelier maria theresa for 12 light",
    linked: "lighting",
    price: 47,
    discountPercentage: 16,
    rating: 4.74,
    thumbnail: "https://i.dummyjson.com/data/products/100/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/100/1.jpg",
      "https://i.dummyjson.com/data/products/100/2.jpg",
      "https://i.dummyjson.com/data/products/100/3.jpg",
      "https://i.dummyjson.com/data/products/100/thumbnail.jpg",
    ],
  },
];

export const ItemDetail4 = [
  {
    id: 86,
    title: "Bluetooth Aux",
    description:
      "Bluetooth Aux Bluetooth Car Aux Car Bluetooth Transmitter Aux Audio Receiver Handfree Car Bluetooth Music Receiver Universal 3.5mm Streaming A2DP Wireless Auto AUX Audio Adapter With Mic For Phone MP3",
    price: 25,
    discountPercentage: 10.56,
    rating: 4.57,
    stock: 22,
    brand: "Car Aux",
    linked: "automotive",
    thumbnail: "https://i.dummyjson.com/data/products/86/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/86/1.jpg",
      "https://i.dummyjson.com/data/products/86/2.webp",
      "https://i.dummyjson.com/data/products/86/3.jpg",
      "https://i.dummyjson.com/data/products/86/4.jpg",
      "https://i.dummyjson.com/data/products/86/thumbnail.jpg",
    ],
  },
  {
    id: 87,
    title: "t Temperature Controller Incubator Controller",
    description:
      "Both Heat and Cool Purpose, Temperature control range; -50 to +110, Temperature measurement accuracy; 0.1, Control accuracy; 0.1",
    price: 40,
    discountPercentage: 11.3,
    rating: 4.54,
    stock: 37,
    brand: "W1209 DC12V",
    linked: "automotive",
    thumbnail: "https://i.dummyjson.com/data/products/87/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/87/1.jpg",
      "https://i.dummyjson.com/data/products/87/2.jpg",
      "https://i.dummyjson.com/data/products/87/3.jpg",
      "https://i.dummyjson.com/data/products/87/4.jpg",
      "https://i.dummyjson.com/data/products/87/thumbnail.jpg",
    ],
  },
  {
    id: 88,
    title: "TC Reusable Silicone Magic Washing Gloves",
    description:
      "TC Reusable Silicone Magic Washing Gloves with Scrubber, Cleaning Brush Scrubber Gloves Heat Resistant Pair for Cleaning of Kitchen, Dishes, Vegetables and Fruits, Bathroom, Car Wash, Pet Care and Multipurpose",
    price: 29,
    discountPercentage: 3.19,
    rating: 4.98,
    stock: 42,
    brand: "TC Reusable",
    linked: "automotive",
    thumbnail: "https://i.dummyjson.com/data/products/88/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/88/1.jpg",
      "https://i.dummyjson.com/data/products/88/2.jpg",
      "https://i.dummyjson.com/data/products/88/3.jpg",
      "https://i.dummyjson.com/data/products/88/4.webp",
      "https://i.dummyjson.com/data/products/88/thumbnail.jpg",
    ],
  },
  {
    id: 89,
    title: "Qualcomm original Car Charger",
    description:
      "best Quality CHarger , Highly Recommended to all best Quality CHarger , Highly Recommended to all",
    price: 40,
    discountPercentage: 17.53,
    rating: 4.2,
    stock: 79,
    brand: "TC Reusable",
    linked: "automotive",
    thumbnail: "https://i.dummyjson.com/data/products/89/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/89/1.jpg",
      "https://i.dummyjson.com/data/products/89/2.jpg",
      "https://i.dummyjson.com/data/products/89/3.jpg",
      "https://i.dummyjson.com/data/products/89/4.jpg",
      "https://i.dummyjson.com/data/products/89/thumbnail.jpg",
    ],
  },
  {
    id: 90,
    title: "Cycle Bike Glow",
    description:
      "Universal fitment and easy to install no special wires, can be easily installed and removed. Fits most standard tyre air stem valves of road, mountain bicycles, motocycles and cars.Bright led will turn on w",
    price: 35,
    discountPercentage: 11.08,
    rating: 4.1,
    stock: 63,
    brand: "Neon LED Light",
    linked: "automotive",
    thumbnail: "https://i.dummyjson.com/data/products/90/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/90/1.jpg",
      "https://i.dummyjson.com/data/products/90/2.jpg",
      "https://i.dummyjson.com/data/products/90/3.jpg",
      "https://i.dummyjson.com/data/products/90/4.jpg",
      "https://i.dummyjson.com/data/products/90/thumbnail.jpg",
    ],
  },
];

export const ItemDetails5 = [
  {
    id: 81,
    title: "Round Silver Frame Sun Glasses",
    description:
      "A pair of sunglasses can protect your eyes from being hurt. For car driving, vacation travel, outdoor activities, social gatherings,",
    price: 19,
    discountPercentage: 10.1,
    rating: 4.94,
    stock: 78,
    brand: "Designer Sun Glasses",
    linked: "sunglasses",
    thumbnail: "https://i.dummyjson.com/data/products/81/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/81/1.jpg",
      "https://i.dummyjson.com/data/products/81/2.jpg",
      "https://i.dummyjson.com/data/products/81/3.jpg",
      "https://i.dummyjson.com/data/products/81/4.webp",
      "https://i.dummyjson.com/data/products/81/thumbnail.jpg",
    ],
  },
  {
    id: 82,
    title: "Kabir Singh Square Sunglass",
    description:
      "Orignal Metal Kabir Singh design 2020 Sunglasses Men Brand Designer Sun Glasses Kabir Singh Square Sunglass",
    price: 50,
    discountPercentage: 15.6,
    rating: 4.62,
    stock: 78,
    brand: "Designer Sun Glasses",
    linked: "sunglasses",
    thumbnail: "https://i.dummyjson.com/data/products/82/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/82/1.jpg",
      "https://i.dummyjson.com/data/products/82/2.webp",
      "https://i.dummyjson.com/data/products/82/3.jpg",
      "https://i.dummyjson.com/data/products/82/4.jpg",
      "https://i.dummyjson.com/data/products/82/thumbnail.jpg",
    ],
  },
  {
    id: 83,
    title: "Wiley X Night Vision Yellow Glasses",
    description:
      "Wiley X Night Vision Yellow Glasses for Riders - Night Vision Anti Fog Driving Glasses - Free Night Glass Cover - Shield Eyes From Dust and Virus- For Night Sport Matches",
    price: 30,
    discountPercentage: 6.33,
    rating: 4.97,
    stock: 115,
    brand: "mastar watch",
    linked: "sunglasses",
    thumbnail: "https://i.dummyjson.com/data/products/83/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/83/1.jpg",
      "https://i.dummyjson.com/data/products/83/2.jpg",
      "https://i.dummyjson.com/data/products/83/3.jpg",
      "https://i.dummyjson.com/data/products/83/4.jpg",
      "https://i.dummyjson.com/data/products/83/thumbnail.jpg",
    ],
  },
  {
    id: 84,
    title: "Square Sunglasses",
    description:
      "Fashion Oversized Square Sunglasses Retro Gradient Big Frame Sunglasses For Women One Piece Gafas Shade Mirror Clear Lens 17059",
    price: 28,
    discountPercentage: 13.89,
    rating: 4.64,
    stock: 64,
    brand: "mastar watch",
    linked: "sunglasses",
    thumbnail: "https://i.dummyjson.com/data/products/84/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/84/1.jpg",
      "https://i.dummyjson.com/data/products/84/2.jpg",
      "https://i.dummyjson.com/data/products/84/thumbnail.jpg",
    ],
  },
  {
    id: 85,
    title: "LouisWill Men Sunglasses",
    description:
      "LouisWill Men Sunglasses Polarized Sunglasses UV400 Sunglasses Day Night Dual Use Safety Driving Night Vision Eyewear AL-MG Frame Sun Glasses with Free Box for Drivers",
    price: 50,
    discountPercentage: 11.27,
    rating: 4.98,
    stock: 92,
    brand: "LouisWill",
    linked: "sunglasses",
    thumbnail: "https://i.dummyjson.com/data/products/85/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/85/1.jpg",
      "https://i.dummyjson.com/data/products/85/2.jpg",
      "https://i.dummyjson.com/data/products/85/thumbnail.jpg",
    ],
  },
];

export const ItemDetails6 = [
  {
    id: 1,
    title: "iPhone 9",
    description: "An apple mobile which is nothing like apple",
    price: 549,
    discountPercentage: 12.96,
    rating: 4.69,
    stock: 94,
    brand: "Apple",
    linked: "smartphones",
    thumbnail: "https://i.dummyjson.com/data/products/1/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/1/1.jpg",
      "https://i.dummyjson.com/data/products/1/2.jpg",
      "https://i.dummyjson.com/data/products/1/3.jpg",
      "https://i.dummyjson.com/data/products/1/4.jpg",
      "https://i.dummyjson.com/data/products/1/thumbnail.jpg",
    ],
  },
  {
    id: 2,
    title: "iPhone X",
    description:
      "SIM-Free, Model A19211 6.5-inch Super Retina HD display with OLED technology A12 Bionic chip with ...",
    price: 899,
    discountPercentage: 17.94,
    rating: 4.44,
    stock: 34,
    brand: "Apple",
    linked: "smartphones",
    thumbnail: "https://i.dummyjson.com/data/products/2/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/2/1.jpg",
      "https://i.dummyjson.com/data/products/2/2.jpg",
      "https://i.dummyjson.com/data/products/2/3.jpg",
      "https://i.dummyjson.com/data/products/2/thumbnail.jpg",
    ],
  },
  {
    id: 3,
    title: "Samsung Universe 9",
    description:
      "Samsung's new variant which goes beyond Galaxy to the Universe",
    price: 1249,
    discountPercentage: 15.46,
    rating: 4.09,
    stock: 36,
    brand: "Samsung",
    linked: "smartphones",
    thumbnail: "https://i.dummyjson.com/data/products/3/thumbnail.jpg",
    images: ["https://i.dummyjson.com/data/products/3/1.jpg"],
  },
  {
    id: 4,
    title: "OPPOF19",
    description: "OPPO F19 is officially announced on April 2021.",
    price: 280,
    discountPercentage: 17.91,
    rating: 4.3,
    stock: 123,
    brand: "OPPO",
    linked: "smartphones",
    thumbnail: "https://i.dummyjson.com/data/products/4/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/4/1.jpg",
      "https://i.dummyjson.com/data/products/4/2.jpg",
      "https://i.dummyjson.com/data/products/4/3.jpg",
      "https://i.dummyjson.com/data/products/4/4.jpg",
      "https://i.dummyjson.com/data/products/4/thumbnail.jpg",
    ],
  },
  {
    id: 5,
    title: "Huawei P30",
    description:
      "Huawei’s re-badged P30 Pro New Edition was officially unveiled yesterday in Germany and now the device has made its way to the UK.",
    price: 499,
    discountPercentage: 10.58,
    rating: 4.09,
    stock: 32,
    brand: "Huawei",
    linked: "smartphones",
    thumbnail: "https://i.dummyjson.com/data/products/5/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/5/1.jpg",
      "https://i.dummyjson.com/data/products/5/2.jpg",
      "https://i.dummyjson.com/data/products/5/3.jpg",
    ],
  },
];

export const ItemDetail7 = [
  {
    img: "https://www.reliancedigital.in/medias/Apple-S8-CLP-Banner-14-11-2022.jpg?context=bWFzdGVyfGltYWdlc3w5NzY3M3xpbWFnZS9qcGVnfGltYWdlcy9oNjAvaDBkLzk5MzExODU1MjA2NzAuanBnfDA3MWZiOGZlMzdjOTYzZDFhZGUyZWMzMjdmOTgxZmJjOGY1MTI2OGI0ZjA3YjU1YzUzNDllZjlkMmQwMmFkMjA",
    caption: "Slide 1",
  },
  {
    img: "https://www.reliancedigital.in/medias/Monitors-Carousel-Banner-02-12-2022.jpg?context=bWFzdGVyfGltYWdlc3w4Mjc4NHxpbWFnZS9qcGVnfGltYWdlcy9oNTEvaDNlLzk5MzExODEzNTkxMzQuanBnfDA5Nzc0YWExYjdjM2YzNTg4Njk4MDJjZGU1ZWQ4NzAzOTIzZDgxMWU2MjVhYjdkNTI2MzBhNWJhYzg0ZTZjMTk",
    caption: "Slide 2",
  },
  {
    img: " https://www.reliancedigital.in/medias/Apple-Accessories-Carousel-Banner-01-12-2022.jpg?context=bWFzdGVyfGltYWdlc3w3MjY3M3xpbWFnZS9qcGVnfGltYWdlcy9oZTIvaDg3Lzk5MjgxNzE1NTI3OTguanBnfDkzOTI0MDE5YzgxOTVmNzdiMTBlNWZhMTQwMWZmNDc1ZTU2MzY5YmIwZTBlZWQ2ZjRkYWVhYzBkZTkzMTM3Y2M",
    caption: "Slide 3",
  },
];

export const ItemDetail8 = [
  {
    img: "https://www.reliancedigital.in/medias/Moto-G42-Carousel-Banner-09-12-2022.jpg?context=bWFzdGVyfGltYWdlc3wxMDMyNDN8aW1hZ2UvanBlZ3xpbWFnZXMvaGQ2L2g2ZC85OTI5ODI3Mzg1Mzc0LmpwZ3w4MzEyODVmNTUyNWIwODNlNTA1YThjNTA4Njg5ZmU1YTU1ZjZlMzM5NWY5ODI0ZWNmOTAwYjY5M2RhNWVkOTky",
    caption: "Slide 1",
  },
  {
    img: "https://www.reliancedigital.in/medias/Winter-Sale-Carousel-Banner-2022.jpg?context=bWFzdGVyfGltYWdlc3w3ODA1OXxpbWFnZS9qcGVnfGltYWdlcy9oOGMvaDU3Lzk5MTgzMzY0MzQyMDYuanBnfDkxOGNjMWJiMjExYWUzYTQ0ODMzMTk5MjQ0YzY0YmVhNTE5ZjQxZTZjNzc4ZTRhNDhjYjc3N2I3NmZjNmM2ZDI",
    caption: "Slide 2",
  },
  {
    img: " https://www.reliancedigital.in/medias/Laptop-Carnival-Carousel-Banner-D.jpg?context=bWFzdGVyfGltYWdlc3w5MTcwNXxpbWFnZS9qcGVnfGltYWdlcy9oM2UvaDJiLzk5MzA5MTgwNjgyNTQuanBnfDM0NDIxMjI1ZmE2NjQ1MDk4MWY2MjJlMjU2Mjg0YzAxNDViYTRiM2YzMTEyYjU5OGUwNTZlNDY4NzcxYzk3M2Y",
    caption: "Slide 3",
  },
];

export const ItemDetails9 = [
  {
    id: 51,
    title: "half sleeves T shirts",
    description:
      "Many store is creating new designs and trend every month and every year. Daraz.pk have a beautiful range of men fashion brands",
    price: 23,
    discountPercentage: 12.76,
    rating: 4.26,
    stock: 132,
    brand: "Vintage Apparel",
    linked: "mens-shirts",
    thumbnail: "https://i.dummyjson.com/data/products/51/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/51/1.png",
      "https://i.dummyjson.com/data/products/51/2.jpg",
      "https://i.dummyjson.com/data/products/51/3.jpg",
      "https://i.dummyjson.com/data/products/51/thumbnail.jpg",
    ],
  },
  {
    id: 52,
    title: "FREE FIRE T Shirt",
    description:
      "quality and professional print - It doesn't just look high quality, it is high quality.",
    price: 10,
    discountPercentage: 14.72,
    rating: 4.52,
    stock: 128,
    brand: "FREE FIRE",
    linked: "mens-shirts",
    thumbnail: "https://i.dummyjson.com/data/products/52/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/52/1.png",
      "https://i.dummyjson.com/data/products/52/2.png",
      "https://i.dummyjson.com/data/products/52/3.jpg",
      "https://i.dummyjson.com/data/products/52/4.jpg",
      "https://i.dummyjson.com/data/products/52/thumbnail.jpg",
    ],
  },
  {
    id: 53,
    title: "printed high quality T shirts",
    description: "Brand: vintage Apparel ,Export quality",
    price: 35,
    discountPercentage: 7.54,
    rating: 4.89,
    stock: 6,
    brand: "Vintage Apparel",
    linked: "mens-shirts",
    thumbnail: "https://i.dummyjson.com/data/products/53/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/53/1.webp",
      "https://i.dummyjson.com/data/products/53/2.jpg",
      "https://i.dummyjson.com/data/products/53/3.jpg",
      "https://i.dummyjson.com/data/products/53/4.jpg",
      "https://i.dummyjson.com/data/products/53/thumbnail.jpg",
    ],
  },
  {
    id: 54,
    title: "Pubg Printed Graphic T-Shirt",
    description:
      "Product Description Features: 100% Ultra soft Polyester Jersey. Vibrant & colorful printing on front. Feels soft as cotton without ever cracking",
    price: 46,
    discountPercentage: 16.44,
    rating: 4.62,
    stock: 136,
    brand: "The Warehouse",
    linked: "mens-shirts",
    thumbnail: "https://i.dummyjson.com/data/products/54/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/54/1.jpg",
      "https://i.dummyjson.com/data/products/54/2.jpg",
      "https://i.dummyjson.com/data/products/54/3.jpg",
      "https://i.dummyjson.com/data/products/54/4.jpg",
      "https://i.dummyjson.com/data/products/54/thumbnail.jpg",
    ],
  },
  {
    id: 55,
    title: "Money Heist Printed Summer T Shirts",
    description: "Fabric Jercy, Size: M & L Wear Stylish Dual Stiched",
    price: 66,
    discountPercentage: 15.97,
    rating: 4.9,
    stock: 122,
    brand: "The Warehouse",
    linked: "mens-shirts",
    thumbnail: "https://i.dummyjson.com/data/products/55/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/55/1.jpg",
      "https://i.dummyjson.com/data/products/55/2.webp",
      "https://i.dummyjson.com/data/products/55/3.jpg",
      "https://i.dummyjson.com/data/products/55/4.jpg",
      "https://i.dummyjson.com/data/products/55/thumbnail.jpg",
    ],
  },
];

export const ItemDetail10 = [
  {
    img: "https://www.reliancedigital.in/medias/iPad-Pro-NPI-Banner-Available-now-27-10-2022.jpg?context=bWFzdGVyfGltYWdlc3wxMDYwNjh8aW1hZ2UvanBlZ3xpbWFnZXMvaDNlL2gyMC85OTEzNjU2NTQxMjE0LmpwZ3wwOTcxYjg0MTc5NDQxNDcwNTRjMzcwNjkxYWJlNGI2NDk3ZjkyYzNhNzM5NWY3NzM0NTRiYjA3ODA1MzRiOWFk",
    caption: "Slide 1",
  },
  {
    img: "https://www.reliancedigital.in/medias/airpods-pro-2nd-gen-Buy-now-NPI-Banner-01-11-2022.jpg?context=bWFzdGVyfGltYWdlc3wxMDM4NjB8aW1hZ2UvanBlZ3xpbWFnZXMvaDQ2L2g2Ny85OTIyNDU2MTkxMDA2LmpwZ3w0MGQxZjFhYjQ0ZjU1NTQzZjJiOGJmYzZhMDg5NTY5M2Y3NzIxZDkzOTQ2Yjg4YmNmOWZlMzc4OWM0YjlkMjA2",
    caption: "Slide 2",
  },
];
